name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  VCPKG_ROOT: ${GITHUB_WORKSPACE}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: echo-env-var
      run: echo "VCPKG_ROOT is $VCPKG_ROOT"
    - name: setup-build-machine
      run: ./scripts/setup-build-machine.sh
    - name: setup-vcpkg
      run: ./setup-vcpkg.sh
