name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup VCPKG_ROOT
      run: echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vcpkg" >> $GITHUB_ENV
    - name: echo-env-var
      run: echo "VCPKG_ROOT is $VCPKG_ROOT"
    - name: Set up Git credentials
      run: |
        git config --global user.name "ryanseghers"
        git config --global user.email "ryanseghers@gmail.com"
        git config --global credential.helper store
        echo "https://$REPO_ACCESS_TOKEN:@github.com" > ~/.git-credentials
    - name: setup-build-machine
      run: ./scripts/setup-build-machine.sh
    - name: build-all
      run: ./build-all.sh
