name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VCPKG_ROOT: ${{ env.GITHUB_WORKSPACE }}
    steps:
    - uses: actions/checkout@v3
    - name: echo-env-var
      run: echo "VCPKG_ROOT is $VCPKG_ROOT"
    - name: setup-build-machine
      run: ./scripts/setup-build-machine.sh
    - name: setup-vcpkg
      run: ./setup-vcpkg.sh
